config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  resources :products
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
  validates :contents, presence: true, length: {maximum: 80}
  
  mount_uploader :new_image, ImageUploader #new_imageカラムにアップローダーの紐付け
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy] #該当メソッドが呼ばれた時はset_productメソッドを先に実行（同じ記述を共通化）
  def index
    @products = Product.all #Productテーブルから全てのデータを取得し、インスタンス変数@productsに格納
  end
  
  def new
    @product = Product.new #Productモデルのインスタンスをnewメソッドで作成、インスタンス変数@productに格納
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  def edit
  end
  
  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  
  def destroy
    @product.destroy
    redirect_to root_path, status: :see_other
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  private
  def product_params
    params.require(:product).permit(:title, :new_image, :hotel_name, :contents)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabimemo02</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <div class="form_area">
    <div class="form_area_title">
    <%= form.label :title, 'タイトル(5文字以上):' %>
    <%= form.text_field :title, size: "30x3" %>
    </div>
    <div class="form_area_name">
    <%= form.label :hotel_name, '宿泊地:' %>
    <%= form.text_field :hotel_name, size: "40x3" %>
    </div>
    <div class="form_area_image">
    <%= form.label :new_image, '画像選択' %>
    <%= form.file_field :new_image %>
    </div>
    <div class="form_area_comment">
      <%= form.label :contents, '感想', class:"comment_title" %>
      <%= form.text_area :contents, size: "50x6" %>
    </div>
    <% if @product.errors.any? %>
      <%= @product.errors.messages[:title][0] %>
    <% end %>
    <div class="form_area_btn">
      <%= form.submit '画像を投稿する', class:"btn_post" %>
    </div>
  </div>
<% end %>

<footer class="footerArea">
    <ul>
      <li><%= link_to "ホーム", root_path, class:"footerLink" %></li>
      <li><%= link_to "新規投稿する", new_product_path, class:"footerLink" %></li>
    </ul>
    <small>&copy; 2023 Tabimemo</small>
  </footer>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit</h1>
<%= render partial: 'form' %>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="お気に入りのホテルをメモしよう">
  <title>tabimemo</title>
  <link rel="icon" href="../../assets/images/jewel_2.png">
  <link rel="stylesheets" href="../../assets/stylesheets/reset.css">
  <link rel="stylesheets" href="../../assets/stylesheets/main.css">
</head>
<body>
  <header class="header">
    <div class="logo">
      <%= link_to root_path do %>
        <%= image_tag 'jewel_2.png', alt: 'logo', width: '70px', height: '70px' %>
      <% end %>
    </div>
    <div class="header-item">
      <ul class="menu">
        <li class="menu-item"><%= link_to "Home", root_path %></li>
      </ul>
    </div>
  </header>
  <div class="top-image">
    <%= image_tag 'bintan.jpg', alt: 'main', width: '80%', height: '200px' %>
  </div>
  <div class="postButton"><%= link_to '新規投稿する', new_product_path, class:"post-btn-link" %></div>
  <div class="wrapper">
    <ul class="contentArea">
      <% @products.each do |product| %>
        <li class="contents">
          <div>
            <%= image_tag product.new_image.url, class:"contentImage", width: '300px', height: '300px' %>
          </div>
          <div class="contentsDetail">
            <%= check_box_tag '', '' %>
            <%= product.title %>
            <%= link_to '[編集]', edit_product_path(product) %>
            <%= link_to '[削除]', product_path(product),
            data: { turbo_method: 'delete', turbo_confirm: '削除してもよろしいですか？' } %><br>
            <div class="hotel_name">宿泊地：<%= product.hotel_name %></div>
            <p class="hotel_text"><%= product.contents %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <footer class="footerArea">
    <ul>
      <li><%= link_to "ホーム", root_path, class:"footerLink" %></li>
      <li><%= link_to "新規投稿する", new_product_path, class:"footerLink" %></li>
    </ul>
    <small>&copy; 2023 Tabimemo</small>
  </footer>
</body>
</html>

app/views/products/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="お気に入りのホテルをメモしよう">
  <title>tabimemo</title>
  <link rel="icon" href="../../assets/images/jewel_2.png">
  <link rel="stylesheets" href="../../assets/stylesheets/reset.css">
  <link rel="stylesheets" href="../../assets/stylesheets/main.css">
</head>
<body>
  <header class="header">
    <div class="logo">
      <%= link_to root_path do %>
        <%= image_tag 'jewel_2.png', alt: 'logo', width: '70px', height: '70px' %>
      <% end %>
    </div>
    <div class="header-item">
      <ul class="menu">
        <li class="menu-item"><%= link_to "Home", root_path %></li>
      </ul>
    </div>
  </header>

<%= render partial: 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= image_tag @product.image.url %>